#!/usr/bin/env bash
# Install and configure Nginx server to:
# - Be listening on port 80
# - Return a page containing the string 'Hello World!' when queried at its root
# - Add a custom header X-Served-By with the server's hostname

# Update apt-get and install Nginx
sudo apt-get -y update
sudo apt-get -y install nginx

# Reconfigure firewall to allow access to the Nginx service
sudo ufw allow 'Nginx HTTP'

# Replace the contents of index.html
echo "Hello World!" | sudo tee /var/www/html/index.html

# Dynamically add a custom header, X-Served-By, with the hostname
sudo sed -i '/server_name _;/a \\n    location / {\n        try_files $uri $uri/ =404;\n        add_header X-Served-By $hostname;\n    }' /etc/nginx/sites-available/default

# Restart Nginx to apply the changes
sudo service nginx restart
